name: Publish Docker build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build --file Dockerfile --tag ghcr.io/jamie6king/porkbun_dns_updater .

      - name: Upload the Docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username jamie6king --password-stdin
          docker push ghcr.io/jamie6king/porkbun_dns_updater